name: "Build with Evolene"
description: "Composite GitHub Actions run step to build a project with Evolene"
inputs:
  project-root:
    description: "Root directory of the checkout repository to build"
    required: true
outputs:
  image:
    description: "Name of the built and pushed image, including registry"
    value: ${{ steps.evolene.outputs.image }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.6"

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Checks-out Evolene to $GITHUB_WORKSPACE/evolene
    #- uses: actions/checkout@v2
    #  with:
    #    repository: KTH/evolene
    #    path: 'evolene'

    # Runs a single command using the runners shell
    - name: Install Evolene dependencies
      run: |
        cd $GITHUB_WORKSPACE
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install

    # Runs a set of commands using the runners shell
    - name: Build with Evolene
      run: |
        cd ${{ inputs.project-root }}
        export EVOLENE_DIRECTORY=$GITHUB_WORKSPACE
        export WORKSPACE=${{ inputs.project-root }}
        $GITHUB_WORKSPACE/run.sh
