# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      # Set our python version
      versionSpec: '3.6'
      addToPath: true
      architecture: 'x64'

        # Upgrade pip
  - bash: pip install --upgrade pip

  # Install pipenv
  - bash: pip install pipenv

  - bash: ./create_dist.sh
    displayName: 'Create dist'

  - bash: echo "##vso[task.setvariable variable=LATEST_DIST]$(ls -tp dist | grep -v / | head -1)"

# -- BUILD CONFIG FROM JENKINS BELOW
#./create_dist.sh
#LATEST_DIST=$(ls -tp dist | grep -v / | head -1)
#tar xvf dist/$LATEST_DIST -C dist
#LATEST_DIR=${LATEST_DIST/.tar.gz/}
#rm -rf dist/latest
#ln -s dist/$LATEST_DIR dist/latest
#cd dist/$LATEST_DIR
#pipenv install