# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      # Set our python version
      versionSpec: '3.6'
      addToPath: true
      architecture: 'x64'

        # Upgrade pip
  - bash: pip install --upgrade pip
    displayName: 'Upgrade pip'

  # Install pipenv
  - bash: pip install pipenv
    displayName: 'Pipenv install'

  - bash: ./create_dist.sh
    displayName: 'Create dist'

  - bash: echo "##vso[task.setvariable variable=LATEST_DIST]$(ls -tp dist | grep -v / | head -1)"
    displayName: 'Create LATEST_DIST variable'

  - bash: tar xvf dist/$LATEST_DIST -C dist
    displayName: 'Create tar of latest dist'

  - bash: echo "##vso[task.setvariable variable=LATEST_DIR]${LATEST_DIST/.tar.gz/}"
    displayName: 'Create LATEST_DIR variable'

  - bash: rm -rf dist/latest
    displayName: 'Remove old latest dist dir'

  - bash: ln -s dist/$LATEST_DIR dist/latest
    displayName: 'Create symbolic link to latest build'

  - bash: cd dist/$LATEST_DIR
    displayName: 'cd into latest_dir'

  - bash: pipenv install
    displayName: 'Run pipenv install for latest dist'
