name: Evolene CI

on: 
  push:
    paths-ignore:
          - '*.md'
          - '*.png'
  workflow_dispatch:

jobs:
  Evolene:
    name: Continuous Integration
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Run Evolene CI pipeline steps
        env:
          SLACK_CHANNELS: "#team-pipeline-build"
          BUILD_INFORMATION_OUTPUT_FILE: "/version.conf"
          PUSH_PUBLIC: True
          BRANCHES_SAVE_STARTING_WITH: 'refs/heads/feature-inject-local-workspace-packages'
          BRANCHES_TAG_AS_MAIN: 'True'
          EVOLENE_TEST_SECRETS: "${{secrets.EVOLENE_TEST_SECRETS}}"
        run: |
          ${{ secrets.EVOLENE_RUN_COMMAND }}

